language: python
cache: pip
python:
  - "3.6"
  - "2.7"
services:
  - redis-server
install:
  - pip install tox-travis
  - pip install -e .
script:
  - tox
  - coverage run --source=redisy -m pytest test.py
  - coverage report -m
after_success:
  - coveralls
